/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.vulture.packagefx;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        Label label = new Label("Hello FX");
        VBox parent = new VBox();
        parent.getChildren().add(label);
        Scene scene = new Scene(parent,400,200);
        stage.setScene(scene);
        stage.show();
    }
}
